package com.sevenheadeddragon.registry;

import com.sevenheadeddragon.SevenHeadedDragon;
import com.sevenheadeddragon.item.SummonItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Registers non-block items: the boss summon item.
 * The 14 custom splash/lingering potion items are auto-generated by vanilla's
 * PotionBrewing/CreativeModeTab machinery once the Potions in ModPotions are
 * registered together with the vanilla POTION/SPLASH_POTION/LINGERING_POTION
 * items - but Forge/vanilla do NOT automatically create separate Item
 * instances per custom Potion type the way blocks/items normally work; the
 * existing minecraft:potion / splash_potion / lingering_potion items are
 * NBT-tag driven (Potion type stored in NBT), so no extra Item registration
 * is required for the potions themselves. See ModPotionRecipes for how
 * players obtain them via brewing.
 */
public final class ModItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, SevenHeadedDragon.MODID);

    public static final RegistryObject<Item> POTION_MASTER_SUMMON = ITEMS.register(
            "potion_master_summon",
            () -> new SummonItem(new Item.Properties().stacksTo(16)));

    private ModItems() {}
}
