package com.sevenheadeddragon.registry;

import com.sevenheadeddragon.SevenHeadedDragon;
import com.sevenheadeddragon.item.EnergyDrinkItem;
import com.sevenheadeddragon.item.SummonItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Registers non-block items: the boss summon item.
 * The 14 custom splash/lingering potion items are auto-generated by vanilla's
 * PotionBrewing/CreativeModeTab machinery once the Potions in ModPotions are
 * registered together with the vanilla POTION/SPLASH_POTION/LINGERING_POTION
 * items - but Forge/vanilla do NOT automatically create separate Item
 * instances per custom Potion type the way blocks/items normally work; the
 * existing minecraft:potion / splash_potion / lingering_potion items are
 * NBT-tag driven (Potion type stored in NBT), so no extra Item registration
 * is required for the potions themselves. See ModPotionRecipes for how
 * players obtain them via brewing.
 */
public final class ModItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, SevenHeadedDragon.MODID);

    public static final RegistryObject<Item> POTION_MASTER_SUMMON = ITEMS.register(
            "potion_master_summon",
            () -> new SummonItem(new Item.Properties().stacksTo(16)));

    /** A ten-minute level IV multi-effect drink. */
    public static final RegistryObject<Item> ENERGY_DRINK = ITEMS.register(
            "energy_drink",
            () -> new EnergyDrinkItem(new Item.Properties()));

    /**
     * Manual summon method for the Fang King, per spec ("手動召喚アイテムはスポーンエッグやコマンドのみ") -
     * no dedicated summon item, just a standard spawn egg.
     */
    public static final RegistryObject<Item> FANG_KING_SPAWN_EGG = ITEMS.register(
            "fang_king_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.FANG_KING, 0x2B2B2B, 0xE8E8E8, new Item.Properties()));

    private ModItems() {}
}
