package com.sevenheadeddragon.registry;

import com.sevenheadeddragon.SevenHeadedDragon;
import com.sevenheadeddragon.item.EnergyDrinkItem;
import com.sevenheadeddragon.item.SummonItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Registers non-block items: the boss summon item.
 * The 14 custom splash/lingering potion items are auto-generated by vanilla's
 * PotionBrewing/CreativeModeTab machinery once the Potions in ModPotions are
 * registered together with the vanilla POTION/SPLASH_POTION/LINGERING_POTION
 * items - but Forge/vanilla do NOT automatically create separate Item
 * instances per custom Potion type the way blocks/items normally work; the
 * existing minecraft:potion / splash_potion / lingering_potion items are
 * NBT-tag driven (Potion type stored in NBT), so no extra Item registration
 * is required for the potions themselves. See ModPotionRecipes for how
 * players obtain them via brewing.
 */
public final class ModItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, SevenHeadedDragon.MODID);

    public static final RegistryObject<Item> POTION_MASTER_SUMMON = ITEMS.register(
            "potion_master_summon",
            () -> new SummonItem(new Item.Properties().stacksTo(16)));

    /** A ten-minute level IV multi-effect drink. */
    public static final RegistryObject<Item> ENERGY_DRINK = ITEMS.register(
            "energy_drink",
            () -> new EnergyDrinkItem(new Item.Properties()));

    /**
     * Manual summon method for the Fang King, per spec ("手動召喚アイテムはスポーンエッグやコマンドのみ") -
     * no dedicated summon item, just a standard spawn egg.
     */
    public static final RegistryObject<Item> FANG_KING_SPAWN_EGG = ITEMS.register(
            "fang_king_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.FANG_KING, 0x2B2B2B, 0xE8E8E8, new Item.Properties()));

    public static final RegistryObject<Item> CENTIPEDE_SPAWN_EGG = ITEMS.register(
            "centipede_black_dragon_eater_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.CENTIPEDE_BOSS, 0x1A1A1A, 0xB22222, new Item.Properties()));

    // ------------------------------------------------------------------
    // 終末の七つ頭の赤い竜 (Apocalypse Seven Headed Red Dragon)
    // ------------------------------------------------------------------

    /**
     * Manual summon for the final boss. Its normal entry point is the
     * "kill 10 zombies under Bad Omen" trigger (see
     * {@code event.RedDragonSpawnHandler}); this egg exists purely for
     * testing/creative use, matching how the Fang King and Centipede are
     * handled.
     */
    public static final RegistryObject<Item> APOCALYPSE_RED_DRAGON_SPAWN_EGG = ITEMS.register(
            "apocalypse_seven_headed_red_dragon_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.APOCALYPSE_RED_DRAGON, 0x8B0000, 0x2A0033,
                    new Item.Properties()));

    public static final RegistryObject<Item> DEBILITATION_MARTYR_SPAWN_EGG = ITEMS.register(
            "debilitation_martyr_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.DEBILITATION_MARTYR, 0x3A3A3A, 0x1B4A2B,
                    new Item.Properties()));

    public static final RegistryObject<Item> TIMED_GIMMICK_CREEPER_SPAWN_EGG = ITEMS.register(
            "timed_gimmick_creeper_spawn_egg",
            () -> new ForgeSpawnEggItem(ModEntities.TIMED_GIMMICK_CREEPER, 0x0DA70B, 0xFF3300,
                    new Item.Properties()));

    private ModItems() {}
}
